# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'ZKPhotoPickerPodDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ZKPhotoPicker', :path => '../'
#  pod 'ZKPhotoPicker', '~> 1.0.1'
  pod 'FLAnimatedImage'

end
