# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ZKPhotoPickerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FLAnimatedImage'
  # Pods for ZKPhotoPickerDemo

end
